### ISSUE TITLE
Server connection issue: "Not ready. Please check your connection"

### ISSUE THREAD

**Issue by MichaelUray** [rustdesk/uptime#5]
It shows me the following error in Austria on multiple locations:
![2024-01-26_19-09-57_WhatsApp_-_Google_Chrome](https://github.com/rustdesk/uptime/assets/25169478/59efcf7f-026f-44ba-ad70-66d42386d808)

Sometimes it changes back to ready, but I am not able to connect.
Then it shows again that it is connecting to the network and it ends with the error message mentioned above.

The server status actually is shown as ok there:
https://rustdesk.github.io/uptime/

**Comment by rustdesk** [comment]
Too crowded.

**Comment by MichaelUray** [comment]
Now it is working again without problems.

So far as I understand use the most of the connections the rendezvous server only to initialize the connection and if whole punching in the NAT firewall worked, then a relay server is not needed.

Was it actually the [Rendezvous Server](https://rustdesk.github.io/uptime/rs-ny.rustdesk.com) which was overloaded, or were it the relay servers?
If it was the rendezvous server, why was there nothing to see at the status page about the issue?
Would an overloaded server not only mean that it would take a bit longer to establish the connection, or how does it influence the RustDesk operation/connection in general?
